### PR TITLE
Fixed console.log() messages

### PR DESCRIPTION
**Pull request by azharakbar**
Replaced console.log with apt return messages

Signed-off-by: Mohammed Azhar Padariyakam <mpadariy@redhat.com>

### CODE REVIEW

**Comment by TheAdnan** [comment]
Actually could you replace the strings with boolean values (true or false)?

**Comment by azharakbar** [comment]
Sure ... :) 
So simply return false ?? 
No need to even log it ?? maybe for debugging ??

**Comment by azharakbar** [comment]
I have made the correction ... 
thanx ... 
is there any other improvements ??

**Comment by TheAdnan** [comment]
Thanks @azharakbar , I'll let you know. Feel free to make a new issue if you see any bugs or improvements.

**Comment by azharakbar** [comment]
Thank U adnan ... Shukran .. :)

**Pull request merged**
