### PR TITLE
Added Feature For Video Download

### PR DESCRIPTION
**Pull request by azharakbar**
Signed-off-by: Mohammed Azhar Padariyakam <mpadariy@redhat.com>

### CODE REVIEW

**Comment by TheAdnan** [comment]
Hey @azharakbar , have you tested this? Does it work?

**Comment by azharakbar** [comment]
Hai @TheAdnan , I have tested the querySelector .. it grabs the video from the insta page ... other all are same as of your original image downloader add on source code ... just changed one line in downloader.js and few lines of description in manifest.json

**Comment by TheAdnan** [comment]
Hey @azharakbar , could you change the pull request to merge into my **video-downloader** branch?

**Comment by azharakbar** [comment]
ook ... :) @TheAdnan

**Comment by azharakbar** [comment]
Done :) @TheAdnan

**Comment by TheAdnan** [comment]
Thanks @azharakbar  🌷

**Comment by azharakbar** [comment]
Thanks @TheAdnan

**Pull request merged**
